export const env = {
  port: Number.parseInt(process.env.PORT || '4000', 10),
  jwtSecret: process.env.JWT_SECRET || 'change-this-secret',
  frontendOrigin: process.env.FRONTEND_ORIGIN || 'http://localhost:5173',
  databaseUrl: process.env.DATABASE_URL || '',
  dbType: process.env.DB_TYPE || 'file',
  transcriptionProvider: process.env.TRANSCRIPTION_PROVIDER || 'groq',
  transcriptionApiKey: process.env.TRANSCRIPTION_API_KEY || process.env.GROQ_API_KEY || '',
  transcriptionModel: process.env.TRANSCRIPTION_MODEL || process.env.GROQ_TRANSCRIPTION_MODEL || 'whisper-large-v3',
  aiProvider: process.env.AI_PROVIDER || 'groq',
  aiApiKey: process.env.AI_API_KEY || process.env.GROQ_API_KEY || process.env.TRANSCRIPTION_API_KEY || '',
  structuredDataModel: process.env.STRUCTURED_DATA_MODEL || process.env.GROQ_STRUCTURED_DATA_MODEL || 'mixtral-8x7b-32768',
  groqApiKey: process.env.GROQ_API_KEY || '',
  groqTranscriptionModel: process.env.GROQ_TRANSCRIPTION_MODEL || 'whisper-large-v3',
  groqStructuredDataModel: process.env.GROQ_STRUCTURED_DATA_MODEL || 'mixtral-8x7b-32768',
  cloudinaryCloudName: process.env.CLOUDINARY_CLOUD_NAME || '',
  cloudinaryApiKey: process.env.CLOUDINARY_API_KEY || '',
  cloudinaryApiSecret: process.env.CLOUDINARY_API_SECRET || '',
  demoPatientId: process.env.DEMO_PATIENT_ID || 'PATIENT001',
  demoPassword: process.env.DEMO_PASSWORD || '123456',
}
