export const env = {
  port: Number.parseInt(process.env.PORT || '4000', 10),
  jwtSecret: process.env.JWT_SECRET || 'change-this-secret',
  frontendOrigin: process.env.FRONTEND_ORIGIN || 'http://localhost:5173',
  databaseUrl: process.env.DATABASE_URL || '',
  dbType: process.env.DB_TYPE || 'file',
  transcriptionProvider: process.env.TRANSCRIPTION_PROVIDER || 'gemini',
  transcriptionApiKey: process.env.TRANSCRIPTION_API_KEY || process.env.GEMINI_API_KEY || '',
  transcriptionModel: process.env.TRANSCRIPTION_MODEL || process.env.GEMINI_TRANSCRIPTION_MODEL || 'gemini-1.5-flash',
  aiProvider: process.env.AI_PROVIDER || 'gemini',
  aiApiKey: process.env.AI_API_KEY || process.env.GEMINI_API_KEY || process.env.TRANSCRIPTION_API_KEY || '',
  structuredDataModel: process.env.STRUCTURED_DATA_MODEL || process.env.GEMINI_STRUCTURED_DATA_MODEL || 'gemini-1.5-flash',
  geminiApiKey: process.env.GEMINI_API_KEY || '',
  geminiTranscriptionModel: process.env.GEMINI_TRANSCRIPTION_MODEL || 'gemini-1.5-flash',
  geminiStructuredDataModel: process.env.GEMINI_STRUCTURED_DATA_MODEL || 'gemini-1.5-flash',
  cloudinaryCloudName: process.env.CLOUDINARY_CLOUD_NAME || '',
  cloudinaryApiKey: process.env.CLOUDINARY_API_KEY || '',
  cloudinaryApiSecret: process.env.CLOUDINARY_API_SECRET || '',
  demoPatientId: process.env.DEMO_PATIENT_ID || 'PATIENT001',
  demoPassword: process.env.DEMO_PASSWORD || '123456',
}
